[package]
name = "amm-domain"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
rust_decimal = { workspace = true }
primitive-types = { workspace = true }
uuid = { workspace = true }
